
export enum Specialite {
    GENERAL_MECHANICS = 'GENERAL_MECHANICS',
    BODYWORK = 'BODYWORK',
    ELECTRICAL_ELECTRONICS = 'ELECTRICAL_ELECTRONICS',
    DIAGNOSTICS = 'DIAGNOSTICS',
    TIRES = 'TIRES'
}
