
export enum Specialite {
  MECANIQUE_GENERALE = 'MECANIQUE_GENERALE',
  CARROSSERIE = 'CARROSSERIE',
  ELECTRICITE_ELECTRONIQUE = 'ELECTRICITE_ELECTRONIQUE',
  DIAGNOSTIC = 'DIAGNOSTIC',
  PNEUMATIQUE = 'PNEUMATIQUE',
}
