
export enum Status {
  RECUE = 'RECUE',
  DIAGNOSTIC_EN_COURS = 'DIAGNOSTIC_EN_COURS',
  DEVIS_A_VALIDER = 'DEVIS_A_VALIDER',
  EN_REPARATION = 'EN_REPARATION',
  TERMINEE = 'TERMINEE',
  RESTITUEE = 'RESTITUEE',
  ANNULEE = 'ANNULEE',
}
