
export enum Status {
  RECEIVED = 'RECEIVED',
  DIAGNOSTIC_IN_PROGRESS = 'DIAGNOSTIC_IN_PROGRESS',
  QUOTATION_TO_VALIDATE = 'QUOTATION_TO_VALIDATE',
  UNDER_REPAIR = 'UNDER_REPAIR',
  COMPLETED = 'COMPLETED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}
